# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import region_pb2 as region__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in region_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShardRaftStub:
    """ShardRaft carries Raft's RequestVote/AppendEntries for one specific
    shard's leader election, tagged by shard_id so a single gRPC server
    can dispatch to the right Raft instance among many hosted per node.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestVote = channel.unary_unary(
                '/dssd.region.v1.ShardRaft/RequestVote',
                request_serializer=region__pb2.ShardVoteRequest.SerializeToString,
                response_deserializer=region__pb2.ShardVoteReply.FromString,
                _registered_method=True)
        self.AppendEntries = channel.unary_unary(
                '/dssd.region.v1.ShardRaft/AppendEntries',
                request_serializer=region__pb2.ShardAppendRequest.SerializeToString,
                response_deserializer=region__pb2.ShardAppendReply.FromString,
                _registered_method=True)


class ShardRaftServicer:
    """ShardRaft carries Raft's RequestVote/AppendEntries for one specific
    shard's leader election, tagged by shard_id so a single gRPC server
    can dispatch to the right Raft instance among many hosted per node.
    """

    def RequestVote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendEntries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShardRaftServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestVote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestVote,
                    request_deserializer=region__pb2.ShardVoteRequest.FromString,
                    response_serializer=region__pb2.ShardVoteReply.SerializeToString,
            ),
            'AppendEntries': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendEntries,
                    request_deserializer=region__pb2.ShardAppendRequest.FromString,
                    response_serializer=region__pb2.ShardAppendReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dssd.region.v1.ShardRaft', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dssd.region.v1.ShardRaft', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShardRaft:
    """ShardRaft carries Raft's RequestVote/AppendEntries for one specific
    shard's leader election, tagged by shard_id so a single gRPC server
    can dispatch to the right Raft instance among many hosted per node.
    """

    @staticmethod
    def RequestVote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.region.v1.ShardRaft/RequestVote',
            region__pb2.ShardVoteRequest.SerializeToString,
            region__pb2.ShardVoteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendEntries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.region.v1.ShardRaft/AppendEntries',
            region__pb2.ShardAppendRequest.SerializeToString,
            region__pb2.ShardAppendReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RegionOwnerStub:
    """RegionOwner is the client-facing API for cross-shard agent hand-off:
    the current owner (leader) of a shard calls this on the destination
    shard's current owner to transfer an agent crossing the boundary.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandOff = channel.unary_unary(
                '/dssd.region.v1.RegionOwner/HandOff',
                request_serializer=region__pb2.HandOffRequest.SerializeToString,
                response_deserializer=region__pb2.HandOffResponse.FromString,
                _registered_method=True)


class RegionOwnerServicer:
    """RegionOwner is the client-facing API for cross-shard agent hand-off:
    the current owner (leader) of a shard calls this on the destination
    shard's current owner to transfer an agent crossing the boundary.
    """

    def HandOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegionOwnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandOff': grpc.unary_unary_rpc_method_handler(
                    servicer.HandOff,
                    request_deserializer=region__pb2.HandOffRequest.FromString,
                    response_serializer=region__pb2.HandOffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dssd.region.v1.RegionOwner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dssd.region.v1.RegionOwner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegionOwner:
    """RegionOwner is the client-facing API for cross-shard agent hand-off:
    the current owner (leader) of a shard calls this on the destination
    shard's current owner to transfer an agent crossing the boundary.
    """

    @staticmethod
    def HandOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dssd.region.v1.RegionOwner/HandOff',
            region__pb2.HandOffRequest.SerializeToString,
            region__pb2.HandOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
