# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dashboard.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dashboard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61shboard.proto\x12\x11\x64ssd.dashboard.v1\"\x12\n\x10GetStatusRequest\"U\n\x11GetStatusResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\r\n\x05round\x18\x02 \x01(\x04\x12\x0c\n\x04loss\x18\x03 \x01(\x02\x12\x10\n\x08has_loss\x18\x04 \x01(\x08\x32\x66\n\x0cWorkerStatus\x12V\n\tGetStatus\x12#.dssd.dashboard.v1.GetStatusRequest\x1a$.dssd.dashboard.v1.GetStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dashboard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETSTATUSREQUEST']._serialized_start=38
  _globals['_GETSTATUSREQUEST']._serialized_end=56
  _globals['_GETSTATUSRESPONSE']._serialized_start=58
  _globals['_GETSTATUSRESPONSE']._serialized_end=143
  _globals['_WORKERSTATUS']._serialized_start=145
  _globals['_WORKERSTATUS']._serialized_end=247
# @@protoc_insertion_point(module_scope)
